### ISSUE TITLE
Allow flexibility in  the development team's name

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2lint#17]
It would be great if q2lint could recognize other development teams, other than `QIIME 2 development team`. Specifically as a flag for the CLI or something else.

**Comment by thermokarst** [comment]
This sounds good to me @ElDeveloper, but, one concern is that this linter is not intended to be general purpose. What I mean by that is that this tool doesn't check for any QIIME 2-specific code or formatting, but rather is making sure that there is a LICENSE (not any license, just the one we have picked for all q2-related projects) and that all source files have a copyright header. I'm not really sure what advantage q2lint would give you w.r.t. q2-american-gut. The "real" linting in QIIME 2 projects comes from `flake8`, otherwise this package is just dotting some "i"s and crossing some "t"s. If you really do want to use this linter in q2-american-gut after all of that, then by all means, we would welcome a PR, I just wanted to make sure we were on the same page about the role of this utility.

**Comment by ElDeveloper** [comment]
> ... this linter is not intended to be general purpose

This pretty much solves it then. Thanks for the info.
